apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.HTTPport }}
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      targetPort: {{ .Values.HTTPport }}
  selector:
      app: {{ .Chart.Name }}

